UserConversation.destroy_all
Message.destroy_all
Conversation.destroy_all
Listing.destroy_all
Plant.destroy_all
User.destroy_all

ActiveRecord::Base.connection.reset_pk_sequence!('user_conversations')
ActiveRecord::Base.connection.reset_pk_sequence!('messages')
ActiveRecord::Base.connection.reset_pk_sequence!('conversations')
ActiveRecord::Base.connection.reset_pk_sequence!('listings')
ActiveRecord::Base.connection.reset_pk_sequence!('plants')
ActiveRecord::Base.connection.reset_pk_sequence!('users')

user1 = User.create(username: 'Ralph', email: 'ralph@test.com', password: '123password', password_confirmation: '123password', location: 'Denver County, CO')
user2 = User.create(username: 'Aedan', email: 'aedan@test.com', password: 'password123', password_confirmation: 'password123', location: 'Denver County, CO')
user3 = User.create(username: 'Brenda', email: 'brenda@test.com', password: 'password2', password_confirmation: 'password2', location: 'Jefferson County, CO')
user4 = User.create(username: 'Emily', email: 'cathleencorcoran@gmail.com', password: 'plantconnect', password_confirmation: 'plantconnect', location: 'Denver County, CO')
user5 = User.create(username: 'Jerry', email: 'planty.raid@yahoo.com', password: 'madprops', password_confirmation: 'madprops', location: 'Denver County, CO')
user6 = User.create(username: 'Katie', email: 'StevenJamesSTL@gmail.com', password: 'seedly', password_confirmation: 'seedly', location: 'Jefferson County, CO')
user7 = User.create(username: 'Katie', email: 'katie_t@test.com', password: 'stemswap', password_confirmation: 'stemswap', location: 'Jefferson County, CO')
user8 = User.create(username: 'Paul', email: 'paul@test.com', password: 'plantydropper', password_confirmation: 'plantydropper', location: 'Jefferson County, CO')
user9 = User.create(username: 'Steven', email: 'HireStevenJames@gmail.com', password: 'nogreenthumbs', password_confirmation: 'nogreenthumbs', location: 'Denver County, CO')
user10 = User.create(username: 'Scott', email: 'scott@turing.edu', password: 'password3', password_confirmation: 'password3', location: 'Denver County, CO')

plant1 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170314001-405dd1ef-d36f-4899-9bea-1877c2f900e0.jpeg", plant_type: "snake plant", indoor: true, user_id: user1.id)
plant2 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170314454-db3c05a6-2628-4213-b655-09abbad3dade.jpeg", plant_type: "chia pet", indoor: true, user_id: user2.id)
plant3 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170314588-e51deb1d-9aaa-4ad5-80e5-9ba897ae3df7.jpeg", plant_type: "rosemary", indoor: false, user_id: user2.id)
plant4 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170314815-7a0a06c3-f137-495d-8b9a-10b91f8f3884.jpeg", plant_type: "sunflower", indoor: false, user_id: user3.id)
plant5 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170315646-54300a68-6c4e-458e-9635-888e7843f333.jpeg", plant_type: "mother of pearl", indoor: true, user_id: user4.id)
plant6 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170316079-95e9f45c-ddcf-43e1-a761-12cda539ed0b.jpeg", plant_type: "cactus", indoor: true, user_id: user5.id)
plant7 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170316343-0f0fe424-f381-41z43-ae5e-46668b33e0e7.jpeg", plant_type: "fiddle leaf fig", indoor: true, user_id: user5.id)
plant8 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170316742-f35cc792-9c98-4eba-9026-1c311c24f5b9.jpeg", plant_type: "spider plant", indoor: true, user_id: user6.id)
plant9 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170317037-11e236c3-e962-4533-982b-3701ce3eb0be.jpeg", plant_type: "monstera", indoor: true, user_id: user6.id)
plant10 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170317465-3e529fec-da97-4ca7-91f3-fc5c323483b6.jpeg", plant_type: "boston fern", indoor: true, user_id: user1.id)
plant11 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170318094-eed427c4-68d0-4e40-835a-5cc172d21835.jpeg", plant_type: "palm", indoor: true, user_id: user7.id)
plant12 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170318254-31826f2e-3ed8-4b92-93a0-1b47ed31fd42.jpeg", plant_type: "aloe vera", indoor: false, user_id: user8.id)
plant13 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170318488-800bdac1-d14d-4613-985d-f36aedb1cc49.jpeg", plant_type: "pothos", indoor: true, user_id: user9.id)
plant14 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170318810-c026537a-64a8-4410-8497-bb104c01e244.jpeg", plant_type: "monstera", indoor: true, user_id: user10.id)
plant15 = Plant.create(photo: "https://user-images.githubusercontent.com/91357724/170319245-d3190377-0608-4cc1-aa78-c17ee5301ca3.jpeg", plant_type: "snake plant", indoor: true, user_id: user10.id)

listing1 = Listing.create(quantity: 7, category: 'clippings', rooted: true, user_id: user1.id, plant_id: plant1.id, description: "Snake plant clippings. I have a bunch available!", active: true)
listing2 = Listing.create(quantity: 1, category: 'plant', rooted: true, user_id: user2.id, plant_id: plant2.id, description: "I am Groot... Sort of.", active: true)
listing3 = Listing.create(quantity: 5, category: 'clippings', rooted: true, user_id: user2.id, plant_id: plant3.id, description: "Rosemary is growing like weeds in my garden. Please take some!", active: true)
listing4 = Listing.create(quantity: 1, category: 'seeds', rooted: false, user_id: user3.id, plant_id: plant4.id, description: "Start your garden with these great seeds!", active: true)
listing5 = Listing.create(quantity: 10, category: 'seeds', rooted: false, user_id: user4.id, plant_id: plant5.id, description: "Mother of Pearl seeds.", active: true)
listing6 = Listing.create(quantity: 1, category: 'plant', rooted: true, user_id: user5.id, plant_id: plant6.id, description: "It's too pokey...", active: true)
listing7 = Listing.create(quantity: 1, category: 'plant', rooted: true, user_id: user5.id, plant_id: plant7.id, description: "Not pokey enough...", active: true)
listing8 = Listing.create(quantity: 4, category: 'clippings', rooted: true, user_id: user6.id, plant_id: plant8.id, description: "Help me contain this thing! ", active: true)
listing9 = Listing.create(quantity: 14, category: 'clippings', rooted: false, user_id: user6.id, plant_id: plant9.id, description: "I'm like Oprah with the free clippings for everyone over here.", active: true)
listing10 = Listing.create(quantity: 2, category: 'clippings', rooted: false, user_id: user1.id, plant_id: plant10.id, description: "You can start your own version of Between Two Ferns.", active: true)
listing11 = Listing.create(quantity: 1, category: 'plant', rooted: true, user_id: user7.id, plant_id: plant11.id, description: "This thing has gotten way too tall for my home.", active: true)
listing12 = Listing.create(quantity: 2, category: 'clippings', rooted: true, user_id: user8.id, plant_id: plant12.id, description: "Great for your sunburns.", active: true)
listing13 = Listing.create(quantity: 1, category: 'clippings', rooted: true, user_id: user9.id, plant_id: plant13.id, description: "I'm running out of friends to give these clippings to. Will you be my new plant friend?", active: true)
listing14 = Listing.create(quantity: 1, category: 'plant', rooted: true, user_id: user10.id, plant_id: plant14.id, description: "Free monstera plant. What else do you really need to know?", active: true)
listing15 = Listing.create(quantity: 1, category: 'plant', rooted: true, user_id: user10.id, plant_id: plant15.id, description: "I named this Planty McPlantface, but it doesn't respond when called. Free to a GREAT home.", active: true)

conversation1 = Conversation.create(listing_id: listing1.id)
conversation2 = Conversation.create(listing_id: listing1.id)
conversation3 = Conversation.create(listing_id: listing10.id)

user1convo1 = UserConversation.create(user_id: user1.id, conversation_id: conversation1.id)
user2convo1 = UserConversation.create(user_id: user2.id, conversation_id: conversation1.id)
user1convo2 = UserConversation.create(user_id: user1.id, conversation_id: conversation2.id)
user3convo2 = UserConversation.create(user_id: user3.id, conversation_id: conversation2.id)
user1convo3 = UserConversation.create(user_id: user1.id, conversation_id: conversation3.id)
user4convo3 = UserConversation.create(user_id: user4.id, conversation_id: conversation3.id)

message1 = Message.create(user_id: user2.id, conversation_id: conversation1.id, content: 'Hi! I would love some of your snake plant clippings. Are they still available?')
message2 = Message.create(user_id: user1.id, conversation_id: conversation1.id, content: 'Absolutely! How many do you need?')
message3 = Message.create(user_id: user2.id, conversation_id: conversation1.id, content: '3?')
message4 = Message.create(user_id: user1.id, conversation_id: conversation1.id, content: 'Works for me. I can put them on my front porch today.')
message5 = Message.create(user_id: user2.id, conversation_id: conversation1.id, content: 'Great. Can you send me your address?')
message6 = Message.create(user_id: user3.id, conversation_id: conversation2.id, content: 'Yo. Hook me up with some clippings!')
message7 = Message.create(user_id: user1.id, conversation_id: conversation2.id, content: 'I still have 4 of them. How many do you want?')
message8 = Message.create(user_id: user4.id, conversation_id: conversation3.id, content: 'Do you still have any clippings left? I love ferns!')
message9 = Message.create(user_id: user1.id, conversation_id: conversation3.id, content: 'I do!')